# Generated by Django 2.0.2 on 2018-02-20 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_api', '0004_auto_20180220_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='date',
            new_name='pub_date',
        ),
    ]
