# Generated by Django 2.0.2 on 2018-02-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_api', '0005_auto_20180220_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.CharField(default='Default summary', max_length=500),
            preserve_default=False,
        ),
    ]
